config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:edit, :update]
  devise_for :users
  resources :user_portfolios
  resources :investment_histories
  root to: 'user_portfolios#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/investment.rb
class Investment < ApplicationRecord
  has_many :user_portfolios
  has_many :investment_services

  scope :search_by_investment_history_param, ->(user_portfolio_id) do
   joins(user_portfolio: :investment_history).where(UserPortfolio.arel_table[:id].eq(user_portfolio_id))
  
  end
end
  

app/models/investment_history.rb
class InvestmentHistory < ApplicationRecord
    belongs_to :user_portfolio
  
    scope :search, ->(investment_id, update_year, update_month) do
      search_by_investment_id(investment_id)
        .search_by_update_year(update_year)
        .search_by_update_month(update_month)
    end
  
    scope :search_by_investment_id, ->(investment_id) do
      return if investment_id.blank?
      joins(user_portfolio: :investment).where(Investment.arel_table[:id].eq(investment_id.to_i))
    end
  
    scope :search_by_update_year, ->(update_year) do
      return if update_year.blank?
      where(InvestmentHistory.arel_table[:update_year].eq(update_year.to_i))
    end
  
    scope :search_by_update_month, ->(update_month) do
      return if update_month.blank?
      where(InvestmentHistory.arel_table[:update_month].eq(update_month.to_i))
    end
  end
  

app/models/investment_service.rb
class InvestmentService < ApplicationRecord
    belongs_to :investment
end

app/models/user.rb
class User < ApplicationRecord
  has_one :user_portfolio
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/models/user_portfolio.rb
class UserPortfolio < ApplicationRecord
    belongs_to :investment
    has_one :investment_history
  end
    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/investment_histories_controller.rb
class InvestmentHistoriesController < ApplicationController
    def index
        @investment_histories = InvestmentHistory.search(params[:investment], params[:year], params[:month])
           
        #/views/investment_histories/index.html.erb内の検索値に初期値を設定する。
        @investment_number = 0
        if(params[:investment])
            @investment_number = Investment.all.find_index(Investment.find_by(id: params[:investment].to_i)) + 1
        end
            @update_year = params[:year]
        @update_month = params[:month]
    end
    
    def show
    end
end

app/controllers/user_portfolios_controller.rb
class UserPortfoliosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_portfolio, only: [:show, :edit, :update, :destroy]

  def index
    @user_portfolio = UserPortfolio.all
    respond_to do |format|
      format.html
      format.csv do
        send_data render_to_string, filename: "user_portfolio.csv", type: :csv
      end
    end
  end

  def new
    @user_portfolio = UserPortfolio.new(user_id: current_user.id)
  end

  def create

    @user_portfolio = UserPortfolio.new(user_portfolio_params)
    if @user_portfolio.save
    end
    redirect_to :action => "index"
  end

  def edit
  end

  def show
  end

  def update
    @user_portfolio.update(total_value: params[:user_portfolio][:total_value].to_i, reserve_value: params[:user_portfolio][:reserve_value].to_i)
    redirect_to("/user_portfolios")
  end

  def destroy
    @user_portfolio.destroy
    redirect_to("/user_portfolios")
  end

  private

  def user_portfolio_params
    params.require(:user_portfolio).permit(:investment_id, :total_value, :reserve_value)
  end

  def set_user_portfolio
    @user_portfolio = UserPortfolio.find_by(id: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  def edit
  end

  def update
    @user.update!(email: params[:user][:email],next_update_day: params[:user][:next_update_day].to_i)

    @user = User.new(params[:user])
    if @user.save
      # Deliver the signup email
      UserNotifier.send_signup_email(@user).deliver
      redirect_to(@user, :notice => 'User created')
    else
      render :action => 'new'
    end
    redirect_to(user_portfolios_path)
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/investment_histories_helper.rb
module InvestmentHistoriesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_portfolio_helper.rb
module UserPortfolioHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/investment_histories/index.html.erb
<div class="container">
 
<%= form_tag(investment_histories_path, :method => 'get' ) do %>
  <%= select_tag :investment, options_from_collection_for_select(Investment.all, "id", "name",@investment_number) %>
  <%= text_field_tag :year ,@update_year%>
  <%= text_field_tag :month ,@update_month%>
  <%= submit_tag '検索', :name => nil %>
<% end %>

  <table class="table table-striped table-sm __web-inspector-hide-shortcut__">
    <thead>
    <tr>
      <th>投資対象</th>
      <th>積立金額</th>
      <th>積立年月</th>
    </tr>
    </thead>
    <% @investment_histories.each do |investment_history| %>
      <tbody>
      <tr>
        <td>
          <%= link_to(
                    "#{investment_history.user_portfolio.investment.name}",
                    "/user_portfolios/#{investment_history.user_portfolio_id}") %>
        </td>
        <td> 
          <%= number_with_delimiter(investment_history.investment_monthly_value) %>
        </td>
        <td>
          <%= "#{investment_history.update_year} 年 #{investment_history.update_month}月" %>
        </td>
      </tr>
      </tbody>
    <% end %>
  </table>
  
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ja">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>Investment Portfolio</title>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="/user_portfolios">Investment Portfolio</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'ユーザー設定', edit_user_path(id: current_user.id) %>  
        </li>
        <li class="nav-item active">
            <%= link_to '月別投資状況', investment_histories_path %>
        </li>
        <li class="nav-item active">
          <%= link_to '投資対象登録', new_user_portfolio_path %>
        </li>
      </ul>
       <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
  <% else %>
      <%= link_to '新規登録 ', new_user_registration_path  %>
      <%= link_to 'ログイン', new_user_session_path  %>
  <% end %>
    </li>
  </div>
</nav>
  <p class="notice"><%= notice %></p> 
  <p class="alert"><%= alert %></p> 
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= yield %>
</body>
</html>

app/views/message/hello.html.erb
<h1>Message#hello</h1>

<p>
  <%= "There is #{@name}'s body." %>, find me in app/views/message_mailer/hello.html.erb
</p>

app/views/message/hello.text.erb
Message#hello

<%= "There is #{@name}'s body." %>, find me in app/views/message_mailer/hello.text.erb

app/views/user_portfolios/edit.html.erb
<div class="container">
    <ul>
        <%= form_for @user_portfolio do |f| %> 投資対象 :
            <%= Investment.find_by(id: @user_portfolio.investment_id).name %><br /> 投資金額 :
            <%= f.text_field :total_value %><br /> 積立金額(月額) :
            <%= f.text_field :reserve_value %><br />
            <%= f.submit %>
        <% end %>
    </ul>
 </div>

app/views/user_portfolios/index.html.erb
<div class="container">
  <%= link_to "csv出力",user_portfolios_path(format: :csv), class: 'btn btn-default' %>
  <table class="table table-striped table-sm __web-inspector-hide-shortcut__">
    <thead>
    <tr>
      <th>投資対象</th>
      <th>サービス名</th>
      <th>投資合計額</th>
      <th>積立月額</th>
      <th>最終更新日</th>
    </tr>
    </thead>
    <% @user_portfolio.each do |portfolio| %>
      <tbody>
      <tr>
        <td>
          <%= link_to(portfolio.investment.name, edit_user_portfolio_path(id: portfolio.id)) %>
        </td>
        <td>
          <%= link_to(InvestmentService.find_by(id: portfolio.investment.investment_service_id).name,
          InvestmentService.find_by(id: portfolio.investment.investment_service_id).service_url) %>
        </td>
        <td>
          <%= number_with_delimiter(portfolio.total_value) %>
        </td>
        <td>
          <%= number_with_delimiter(portfolio.reserve_value) %>
        </td>
        <td> <%= portfolio.updated_at.strftime("%Y-%m-%d(%a)") %>
        </td>
      </tr>
      </tbody>
    <% end %>
  </table> 
</div>

app/views/user_portfolios/new.html.erb
<div class="container">
    <ul>
        <%= form_for @user_portfolio do |f| %> 投資対象を選んでください :
         <%= f.collection_select :investment_id, Investment.all,:id, :name %><br /> 既に投資済みの金額を入力してください :
         <%= f.text_field :total_value %><br /> 積み立てをする場合は金額を入力してください(月額) :
         <%= f.text_field :reserve_value %><br />
         <%= f.submit %>
        <% end %>
     </ul>       
</div>

app/views/user_portfolios/show.html.erb
<div class="container">
  <ul class="list-group">
    <li class="list-group-item"> 投資対象 : <%= Investment.find_by(id: @user_portfolio.investment_id).name %></li>
    <li class="list-group-item"> 投資金額 : <%= @user_portfolio.total_value %></li>
    <li class="list-group-item"> 積立金額(月額) : <%= @user_portfolio.reserve_value %></li>
    <li class="list-group-item"> <%= link_to("編集", "edit") %></li>
    <li class="list-group-item"> <%= link_to "削除", user_portfolio_path(@user_portfolio), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  </ul>
</div>

app/views/users/edit.html.erb
<div class="container">
    <ul>
        <%= form_for @user do |f| %>
            メールアドレス :<%= f.text_field :email %><br /> 
            次回積立更新日 :<%= f.select :next_update_day, [['1日',1],['5日',5],['15日',15],['25日',25]]%><br />
            <%= f.submit %>
        <% end %>
    </ul>
 </div>
 <%= link_to 'パスワードの変更はこちら', edit_user_registration_path %>